### PR TITLE
Add `egobox.Egor` optimizer interface

### PR DESCRIPTION
**Pull request by relf**
This PR adds `Egor` optimizer from [egobox library](https://pypi.org/project/egobox) interface.
Egor is a bayesian optimizer handling single-objective, constrained problems with mixed-discrete variables (continuous relaxation). 

- [x] Initial implementation
- [x] Documentation
- [x] More tests / cleanup
- [x] Read and sign the [Contributor License Agreement (CLA)](https://github.com/jbussemaker/SBArchOpt/blob/main/SBArchOpt%20DLR%20Individual%20Contributor%20License%20Agreement.docx) , and send it to the project coordinator

### CODE REVIEW

**Comment by jbussemaker** [comment]
Thanks @relf :)

I see that there are still some items to be done, but looking at the code it seems already quite feature complete.
Some small improvements for now:
- You can use the functions/classes in `algo/pymoo_interface/storage_restart.py` for managing storage/restart
  - The problem class load/store functions are problem-specific optional implementations
  - `load_from_previous_results` (in `storage_restart.py`) uses a problem-agnostic load function if the above is not available
  - You can use `ArchOptEvaluator` to enable intermediate result storage, or `ArchOptEvaluator.store_pop(pop)` to manually trigger storing the current population
- You can add `egor` to the list of optional dependencies in the tests.yml (line 40) and tests_slow.yml (line 37) CI/CD workflows

**Comment by jbussemaker** [comment]
Hmm that is weird, the evaluator (which is an extension of pymoo's `Evaluator` class) normally always works with multiple design points to evaluate.

Maybe something is going wrong when instantiating the `Population`? Double check that the Population indeed contains multiple design points and that all the design variables match their definition etc.

**Comment by relf** [comment]
Forget what I said. You're right, I have just tested now and it just works fine.

**Comment by relf** [comment]
I've added egobox 0.14.0 distribution on macos. Hopefully the failed job should pass now.

**Review by jbussemaker — APPROVED** [review]

**Pull request merged**
